{application,config,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{config_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[apps,config_app,config_server,config_sup,deployment,
                        host]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
